var fs = require('fs');


exports.collectJob = function(req,res){
	var collectJob = {
		job :[
			{
				"jobName":"设计师",
				"time":"2017-05-04",
				"money":"20k-30k",
				"experice":"3-5年",
				"record":"本科",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市马克菠萝有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"500-1000人",
				"conllectStatus":0
			},
			{
				"jobName":"木材师",
				"time":"2017-02-17",
				"money":"6k-10k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":1
			},
			{
				"jobName":"工程师",
				"time":"2017-03-18",
				"money":"8k-10k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":1
			},
			{
				"jobName":"建筑师",
				"time":"2017-06-17",
				"money":"10k-15k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":3
			},
			{
				"jobName":"金属师",
				"time":"2017-02-17",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":0
			},
			{
				"jobName":"魔法师",
				"time":"2017-02-17",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":1
			},
			{
				"jobName":"老师",
				"time":"2016-09-17",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":3
			},
			{
				"jobName":"木材师",
				"time":"2014-12-17",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"东莞市百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":1
			},
			{
				"jobName":"西伯利亚师",
				"time":"2014-06-06",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"广州多益有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"50-100人",
				"conllectStatus":2
			},
			{
				"jobName":"罗师",
				"time":"2015-04-17",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"广州新浪百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"50-100人",
				"conllectStatus":2
			},
			{
				"jobName":"木材师",
				"time":"2016-02-28",
				"money":"12k-20k",
				"experice":"3-5年",
				"record":"大专",
				"tags":['定制','橱柜衣柜','研发设计','3dMax'],
				"companyName":"深圳腾讯百度有限公司",
				"resumeJob":"橱柜/卫浴/定制家具",
				"companySize":"150-300人",
				"conllectStatus":1
			}
		]
	}
	res.send(collectJob);
}